[development]
DB_HOST = "18.191.159.163"
LOG_FILE = "C:\\Users\\jpeng\\Documents\\business\\kongyiji\\kongbot\\output.log"
LLM_LOG_FILE = "C:\\Users\\jpeng\\Documents\\business\\kongyiji\\kongbot\\llm_output.log"

# DEBUG = 10
# INFO = 20
# WARNING = 30
# ERROR = 40
# CRITICAL = 50
LOG_LEVEL = 10 

API_HOST = "localhost"
API_PORT = 8000

[production]
DB_HOST = "172.31.34.171"
API_HOST = "0.0.0.0"
API_PORT = 8000
